#ifndef _BOARDS_BOARD_CFG_H
#define _BOARDS_BOARD_CFG_H

#define PICO_RP2350A 0
#define PICO_FLASH_SIZE_BYTES (2 * 1024 * 1024)
#define PICO_XOSC_STARTUP_DELAY_MULTIPLIER 64

#endif // _BOARDS_BOARD_CFG_H